name: Gass Lab
favicon: null
layout_spectrum: 0.9892473
typography_spectrum: 0.2580645
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020100'
    - '#441a04'
    - '#765b24'
    - '#828154'
    - '#081553'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
