name: The Gass Lab
favicon: null
layout_spectrum: 0.718638
typography_spectrum: 0.46807
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#011F5F'
    - '#382913'
    - '#6982B8'
    - '#A1B0EA'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
