purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5625
  brandStrength: 0.8125
  rhythmicContrast: 0
  brandColors:
    - '#000000'
    - '#011F5F'
    - '#382913'
    - '#6982B8'
    - '#A1B0EA'
  lightness: 0.5625
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: The Gass Lab
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.46807
layout_spectrum: 1
