favicon: null
name: The Gass Lab
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.1875
  brandStrength: 0.25
  rhythmicContrast: 0
  brandColors:
    - '#8d9799'
    - '#040404'
    - '#445f87'
    - '#8d473a'
    - '#d1d0d6'
  lightness: 0.5
typography_spectrum: 0.50012
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.718638
analytics:
  twitter: null
  google: null
  facebook: null
