favicon: null
name: The Gass Lab
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5488722
  brandStrength: 0.4987469
  lightness: 0.5081454
  brandColors:
    - '#000000'
    - '#011F5F'
    - '#382913'
    - '#6982B8'
    - '#A1B0EA'
  rhythmicContrast: 0
typography_spectrum: 0.50012
layout_spectrum: 0.718638
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
